name: Notion Sync

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run sync
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        GITHUB_REPO: "HyxiaoGe/notion-notes"
        TZ: 'Asia/Shanghai'
      run: | 
        python main.py || exit 1  # 添加错误处理
